#Movies
@domain = http://localhost:3000/
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDM3ODA0ODN9.0xEZ97Emfyxp6PEr1IzDqfdu1R8fTcqwlJRjG3qH-4s
### Displays movie index
GET {{domain}}/movies

### Displays selected movie
GET {{domain}}/movies/1

### same as above
GET {{domain}}/movie?id=2

### creates a new movie instance
POST {{domain}}/movies
Content-Type: application/json

{
  "title": "bobby",
  "year": 6666,
  "plot": "nonsens"
}

### Updates a movie instance
PATCH {{domain}}/movies/1
Content-Type: application/json

{
 "english": true
}

### Deletes a movie instance
DELETE {{domain}}/movies/6

# Actors

### Displays actor index
GET {{domain}}/actors

### Displays selected actor
GET {{domain}}/actors/13

### same as above
GET {{domain}}/actor?id=14

### creates a new actor instance
POST {{domain}}/actors
Content-Type: application/json

{
  "first_name": "Benedict",
  "last_name": "Cumberbatch",
  "known_for": "Sherlock"
}

### Updates a actor instance
PATCH {{domain}}/actors/14
Content-Type: application/json

{
  "gender": "Male",
  "age": 45
}

###  Deletes a actor instance
DELETE {{domain}}/actors/12

### Users create (signup)
POST {{domain}}users
Content-Type: application/json

{
  "name": "gavin",
  "email": "gavin@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "password"
}

### movies create
POST {{domain}}movies
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "title": "poor man",
  "year": 2021,
  "plot": "random story about a man who's poor ",
  "director": "example",
  "english": true
}
### movie genres create 
POST {{domain}}genres
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "movie_id": 4,
  "genre_id": 2
} 
